export const SUCCESS = 200;
export const ERROR = 500;

export const ON_CREATE_ROOM = 'CREATE_ROOM';
export const ON_JOIN_ROOM = 'JOIN_ROOM';
export const ON_LEAVE_ROOM = 'LEAVE_ROOM';
export const ON_START_GAME = 'START_GAME';
export const ON_DEAL_CARD = 'DEAL_CARD';
export const ON_BET_COIN = 'BET_COIN';
export const ON_FOLD_CARD = 'FOLD_CARD';
export const ON_FINISH_GAME = 'FINISH_GAME';

export const EMIT_START = 'GET_START_GAME';
export const EMIT_GAME_RESULT = 'GET_GAME_RESULT';
export const EMIT_CARD_DEAL = 'GET_CARD_DEAL';
export const EMIT_PLAYER_JOIN = 'GET_PLAYER_JOIN';
export const EMIT_PLAYER_LEAVE = 'GET_PLAYER_LEAVE';
export const EMIT_BETTING = 'GET_BET_COIN';
export const EMIT_FOLDING = 'GET_FOLD_CARD';
export const ON_PLAYER_READY = 'PLAYER_READY';
export const EMIT_PLAYER_READY = 'GET_PLAYER_READY';
export const SOCKET_ERROR = 'SOCKET_ERROR';

export const ON_PLAYER_ACTION = 'PLAYER_ACTION';
export const EMIT_PLAYER_ACTION = 'GET_PLAYER_ACTION';
export const EMIT_BETTING_ROUND_END = 'GET_BETTING_ROUND_END';

export const ON_DECLARE_POT = 'DECLARE_POT';
export const ON_SUBMIT_EQUATION = 'SUBMIT_EQUATION';
export const EMIT_DECLARE_POT = 'GET_DECLARE_POT';
export const EMIT_SUBMIT_EQUATION = 'GET_SUBMIT_EQUATION';
export const EMIT_DECLARE_PHASE_START = 'GET_DECLARE_PHASE_START';
export const EMIT_SHOWDOWN_RESULT = 'GET_SHOWDOWN_RESULT';
