'use strict';
const SUCCESS = 200;
const ERROR = 500;
const ON_CREATE_ROOM = 'CREATE_ROOM';
const ON_JOIN_ROOM = 'JOIN_ROOM';
const ON_LEAVE_ROOM = 'LEAVE_ROOM';
const ON_START_GAME = 'START_GAME';
const ON_DEAL_CARD = 'DEAL_CARD';
const ON_BET_COIN = 'BET_COIN';
const ON_FOLD_CARD = 'FOLD_CARD';
const ON_FINISH_GAME = 'FINISH_GAME';
const EMIT_CREATE_ROOM = 'EMIT_CREATE_ROOM';
const EMIT_START = 'EMIT_START_GAME';
const EMIT_GAME_RESULT = 'GET_GAME_RESULT';
const EMIT_CARD_DEAL = 'GET_CARD_DEAL';
const EMIT_PLAYER_JOIN = 'PLAYER_JOIN';
const EMIT_PLAYER_LEAVE = 'PLAYER_LEAVE';
const EMIT_BETTING = 'EMIT_BET_COIN';
const EMIT_FOLDING = 'EMIT_FOLD_CARD';

module.exports = {
    SUCCESS,
    ERROR,
    ON_CREATE_ROOM,
    ON_JOIN_ROOM,
    ON_LEAVE_ROOM,
    ON_START_GAME,
    ON_DEAL_CARD,
    ON_BET_COIN,
    ON_FOLD_CARD,
    ON_FINISH_GAME,
    EMIT_CREATE_ROOM,
    EMIT_START,
    EMIT_GAME_RESULT,
    EMIT_CARD_DEAL,
    EMIT_PLAYER_JOIN,
    EMIT_PLAYER_LEAVE,
    EMIT_BETTING,
    EMIT_FOLDING
};
