'use strict';
const EMIT_CREATE_ROOM = 'CREATE_ROOM';
const EMIT_JOIN_ROOM = 'JOIN_ROOM';
const EMIT_LEAVE_ROOM = 'LEAVE_ROOM';
const EMIT_START_GAME = 'START_GAME';
const EMIT_DEAL_CARD = 'DEAL_CARD';
const EMIT_BET_COIN = 'BET_COIN';
const EMIT_FOLD_CARD = 'FOLD_CARD';
const EMIT_FINISH_GAME = 'FINISH_GAME';

const EMIT_PLAYER_READY = 'PLAYER_READY';

const ON_START = 'GET_START_GAME';
const ON_GAME_RESULT = 'GET_GAME_RESULT';
const ON_CARD_DEAL = 'GET_CARD_DEAL';
const ON_PLAYER_JOIN = 'GET_PLAYER_JOIN';
const ON_PLAYER_LEAVE = 'GET_PLAYER_LEAVE';
const ON_PLAYER_READY = 'GET_PLAYER_READY';
const ON_BETTING = 'GET_BET_COIN';
const ON_FOLDING = 'GET_FOLD_CARD';
const SOCKET_ERROR = 'SOCKET_ERROR';

const EMIT_PLAYER_ACTION = 'PLAYER_ACTION';
const ON_PLAYER_ACTION = 'GET_PLAYER_ACTION';
const ON_BETTING_ROUND_END = 'GET_BETTING_ROUND_END';

export {
    EMIT_CREATE_ROOM,
    EMIT_JOIN_ROOM,
    EMIT_LEAVE_ROOM,
    EMIT_START_GAME,
    EMIT_DEAL_CARD,
    EMIT_BET_COIN,
    EMIT_FOLD_CARD,
    EMIT_FINISH_GAME,
    EMIT_PLAYER_READY,
    ON_START,
    ON_GAME_RESULT,
    ON_CARD_DEAL,
    ON_PLAYER_JOIN,
    ON_PLAYER_LEAVE,
    ON_PLAYER_READY,
    ON_BETTING,
    ON_FOLDING,
    SOCKET_ERROR,
    EMIT_PLAYER_ACTION,
    ON_PLAYER_ACTION,
    ON_BETTING_ROUND_END,
};
